# Generated by Django 6.0.1 on 2026-01-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="absence_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto de la multa aplicada cuando un modelo no se presenta",
                max_digits=10,
                verbose_name="Multa por Ausencia (COP)",
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="late_penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto de la multa aplicada cuando un modelo llega tarde",
                max_digits=10,
                verbose_name="Multa por Retraso (COP)",
            ),
        ),
    ]
