# Generated by Django 6.0.1 on 2026-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0002_agency_absence_penalty_agency_late_penalty"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="bank_fee_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje de comisiones bancarias aplicadas a las transacciones",
                max_digits=5,
                verbose_name="Porcentaje de Comisiones Bancarias (%)",
            ),
        ),
        migrations.AddField(
            model_name="agency",
            name="model_gain_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Porcentaje que reciben los modelos de sus ganancias",
                max_digits=5,
                verbose_name="Porcentaje de Ganancia de Modelos (%)",
            ),
        ),
    ]
