# Generated by Django 6.0.1 on 2026-01-19 17:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_agency_bank_fee_percentage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descripción de la regla de bonus",
                        max_length=200,
                        verbose_name="Nombre de la Regla",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Diario"),
                            ("WEEKLY", "Semanal"),
                            ("MONTH_FIRST_HALF", "Del 1 al 15 del mes"),
                            ("MONTH_SECOND_HALF", "Del 16 al fin del mes"),
                            ("MONTHLY", "Mensual"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Período",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto objetivo de ganancia total para activar el bonus",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Objetivo (COP)",
                    ),
                ),
                (
                    "bonus_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Porcentaje de Ganancia Total"),
                            ("FIXED_AMOUNT", "Monto Fijo"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Bonus",
                    ),
                ),
                (
                    "bonus_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje (%) o monto fijo (COP) según el tipo seleccionado",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor del Bonus",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bonus_rules",
                        to="agencies.agency",
                        verbose_name="Agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de Bonus",
                "verbose_name_plural": "Reglas de Bonus",
                "ordering": ["agency", "period_type", "-created_at"],
            },
        ),
    ]
