# Generated by Django 6.0.1 on 2026-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0004_bonusrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bonusrule",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("DAILY", "Diario"),
                    ("WEEKLY", "Semanal"),
                    ("BIWEEKLY", "Quincenal (2 veces al mes)"),
                    ("MONTHLY", "Mensual"),
                ],
                max_length=20,
                verbose_name="Tipo de Período",
            ),
        ),
    ]
