# Generated by Django 6.0.1 on 2026-01-20 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0005_alter_bonusrule_period_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bonusrule",
            name="target_currency",
            field=models.CharField(
                choices=[("COP", "COP (Pesos Colombianos)"), ("USD", "USD (Dólares)")],
                default="COP",
                help_text="Moneda en la que se define el objetivo (COP o USD)",
                max_length=3,
                verbose_name="Moneda del Objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="bonusrule",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Monto objetivo de ganancia total para activar el bonus",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Objetivo",
            ),
        ),
    ]
