# Generated by Django 6.0.1 on 2026-01-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_bonusrule_order_and_stop_on_match"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bonusrule",
            options={
                "ordering": ["agency", "order", "period_type", "-created_at"],
                "verbose_name": "Regla de Bonus",
                "verbose_name_plural": "Reglas de Bonus",
            },
        ),
        migrations.AlterField(
            model_name="bonusrule",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Orden de aplicación de la regla (menor número = se aplica primero)",
                verbose_name="Orden",
            ),
        ),
        migrations.AlterField(
            model_name="bonusrule",
            name="stop_on_match",
            field=models.BooleanField(
                default=False,
                help_text="Si esta regla se aplica, no se evaluarán las reglas siguientes",
                verbose_name="Detener en esta regla",
            ),
        ),
    ]
