# Generated by Django 6.0.1 on 2026-01-19 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_modelgain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkedHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Número de horas trabajadas (puede incluir decimales, ej: 7.5)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worked_hours_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worked_hours",
                        to="models_app.model",
                        verbose_name="Modelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horas Trabajadas",
                "verbose_name_plural": "Horas Trabajadas",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["model", "date"], name="models_app__model_i_6eb6e1_idx"
                    ),
                    models.Index(fields=["date"], name="models_app__date_6ffa78_idx"),
                ],
                "unique_together": {("model", "date")},
            },
        ),
    ]
