# Generated by Django 6.0.1 on 2026-01-19 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0002_agency_absence_penalty_agency_late_penalty"),
        ("models_app", "0003_workedhours"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ej: Matutino, Vespertino, Nocturno",
                        max_length=100,
                        verbose_name="Nombre del Horario",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Hora de Inicio")),
                ("end_time", models.TimeField(verbose_name="Hora de Fin")),
                (
                    "meal_break_start",
                    models.TimeField(
                        blank=True,
                        help_text="Hora flexible de inicio del descanso para comida",
                        null=True,
                        verbose_name="Hora de Inicio del Descanso para Comida",
                    ),
                ),
                (
                    "meal_break_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Duración del descanso para comida (ej: 01:00:00 para 1 hora)",
                        null=True,
                        verbose_name="Duración del Descanso para Comida",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="agencies.agency",
                        verbose_name="Agencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario",
                "verbose_name_plural": "Horarios",
                "ordering": ["agency", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_assignments",
                        to="models_app.model",
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="models_app.schedule",
                        verbose_name="Horario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Horario",
                "verbose_name_plural": "Asignaciones de Horarios",
                "ordering": ["-date", "schedule__start_time"],
            },
        ),
        migrations.CreateModel(
            name="WorkSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("STARTED", "Iniciada"),
                            ("ON_BREAK", "En Pausa"),
                            ("ON_MEAL", "En Descanso para Comida"),
                            ("COMPLETED", "Completada"),
                            ("ABSENT", "Ausente"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "actual_arrival_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Confirmación de presencia por el manager",
                        null=True,
                        verbose_name="Hora de Llegada Real",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="Minutos de Retraso"),
                ),
                (
                    "break_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Inicio de Pausa"
                    ),
                ),
                (
                    "break_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de Pausa"
                    ),
                ),
                (
                    "meal_start",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Inicio de Descanso para Comida",
                    ),
                ),
                (
                    "meal_end",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Fin de Descanso para Comida",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Clôture par le manager",
                        null=True,
                        verbose_name="Hora de Fin",
                    ),
                ),
                (
                    "total_worked_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Horas Totales Trabajadas",
                    ),
                ),
                (
                    "late_penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Monto de Multa por Retraso",
                    ),
                ),
                (
                    "absence_penalty_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Monto de Multa por Ausencia",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to="models_app.model",
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "schedule_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_sessions",
                        to="models_app.scheduleassignment",
                        verbose_name="Asignación de Horario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Trabajo",
                "verbose_name_plural": "Sesiones de Trabajo",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(
                fields=["agency", "is_active"], name="models_app__agency__9da229_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleassignment",
            index=models.Index(
                fields=["model", "date"], name="models_app__model_i_6e421a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleassignment",
            index=models.Index(fields=["date"], name="models_app__date_4d38e5_idx"),
        ),
        migrations.AddIndex(
            model_name="scheduleassignment",
            index=models.Index(
                fields=["schedule"], name="models_app__schedul_db0f47_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduleassignment",
            unique_together={("model", "date")},
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(
                fields=["model", "date"], name="models_app__model_i_94b85e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(fields=["date"], name="models_app__date_9dc0a8_idx"),
        ),
        migrations.AddIndex(
            model_name="worksession",
            index=models.Index(fields=["status"], name="models_app__status_303b10_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="worksession",
            unique_together={("model", "date")},
        ),
    ]
