# Generated by Django 6.0.1 on 2026-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0005_schedule_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="meal_break_start",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="meal_break_duration",
            field=models.DurationField(
                blank=True,
                help_text="Duración prevista del descanso para comida (ej: 01:00:00 para 1 hora). El inicio y fin se registran mediante botones.",
                null=True,
                verbose_name="Duración del Descanso para Comida",
            ),
        ),
    ]
