# Generated by Django 6.0.1 on 2026-01-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0006_remove_schedule_meal_break_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="coaching_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fin de Coaching"
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="coaching_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Inicio de Coaching"
            ),
        ),
        migrations.AlterField(
            model_name="worksession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("STARTED", "Iniciada"),
                    ("ON_BREAK", "En Pausa"),
                    ("ON_MEAL", "En Descanso para Comida"),
                    ("ON_COACHING", "En Coaching"),
                    ("COMPLETED", "Completada"),
                    ("ABSENT", "Ausente"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
