# Generated by Django 6.0.1 on 2026-01-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "models_app",
            "0007_worksession_coaching_end_worksession_coaching_start_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pause_type",
                    models.CharField(
                        choices=[
                            ("BREAK", "Pausa Normal"),
                            ("MEAL", "Pausa Comida"),
                            ("COACHING", "Coaching"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Pausa",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Hora de Inicio")),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de Fin"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
                (
                    "work_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pauses",
                        to="models_app.worksession",
                        verbose_name="Sesión de Trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pausa",
                "verbose_name_plural": "Pausas",
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["work_session", "pause_type"],
                        name="models_app__work_se_1f9e8d_idx",
                    )
                ],
            },
        ),
    ]
