# Generated by Django 6.0.1 on 2026-01-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0008_pause"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="week_days",
            field=models.CharField(
                blank=True,
                help_text="Días de la semana separados por comas (ej: Lunes,Martes,Miércoles)",
                max_length=100,
                verbose_name="Días de la Semana",
            ),
        ),
    ]
