# Generated by Django 6.0.1 on 2026-01-19 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0009_schedule_week_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleassignment",
            options={
                "ordering": ["schedule__start_time", "model__first_name"],
                "verbose_name": "Asignación de Horario",
                "verbose_name_plural": "Asignaciones de Horarios",
            },
        ),
        migrations.RemoveIndex(
            model_name="scheduleassignment",
            name="models_app__model_i_6e421a_idx",
        ),
        migrations.RemoveIndex(
            model_name="scheduleassignment",
            name="models_app__date_4d38e5_idx",
        ),
        migrations.AlterUniqueTogether(
            name="scheduleassignment",
            unique_together={("model", "schedule")},
        ),
        migrations.AddField(
            model_name="scheduleassignment",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Si está inactivo, no se crearán sesiones de trabajo para esta asignación",
                verbose_name="Activo",
            ),
        ),
        migrations.AlterField(
            model_name="worksession",
            name="schedule_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Asignación récurrente (peut être null pour compatibilité)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_sessions",
                to="models_app.scheduleassignment",
                verbose_name="Asignación de Horario",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleassignment",
            index=models.Index(
                fields=["model", "schedule"], name="models_app__model_i_9f33e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleassignment",
            index=models.Index(
                fields=["is_active"], name="models_app__is_acti_0e5caf_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="scheduleassignment",
            name="date",
        ),
    ]
