# Generated by Django 6.0.1 on 2026-01-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0010_alter_scheduleassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worksession",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("STARTED", "Iniciada"),
                    ("ON_BREAK", "En Pausa"),
                    ("ON_MEAL", "En Descanso para Comida"),
                    ("ON_COACHING", "En Coaching"),
                    ("COMPLETED", "Completada"),
                    ("ABSENT", "Ausente"),
                    ("ABSENT_APPROVED", "Ausente Aprobada"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
