# Generated by Django 6.0.1 on 2026-01-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0011_alter_worksession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="bank_fee_percentage_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje sauvegardé au moment de la complétion",
                max_digits=5,
                null=True,
                verbose_name="Porcentaje de Gastos Bancarios (Snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="model_gain_percentage_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje sauvegardé au moment de la complétion",
                max_digits=5,
                null=True,
                verbose_name="Porcentaje de Ganancia del Modelo (Snapshot)",
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="session_bank_fees",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Gastos bancarios calculés pour cette session",
                max_digits=12,
                verbose_name="Gastos Bancarios de la Sesión (COP)",
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="session_gain_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ganancia total de cette session, sauvegardée au moment de la complétion",
                max_digits=12,
                verbose_name="Ganancia de la Sesión (COP)",
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="session_model_ganancia",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ganancia final del modelo pour cette session",
                max_digits=12,
                verbose_name="Ganancia del Modelo de la Sesión (COP)",
            ),
        ),
    ]
