# Generated by Django 6.0.1 on 2026-01-19 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0012_worksession_bank_fee_percentage_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="cedula",
            field=models.CharField(
                blank=True,
                help_text="Número de identificación",
                max_length=20,
                null=True,
                verbose_name="Cédula",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="edad",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Edad",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="eps",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NUEVA_EPS", "Nueva EPS"),
                    ("SANITAS", "Sanitas"),
                    ("PONAL", "Ponal"),
                    ("FAMISANAR", "Famisanar"),
                    ("SALUD_TOTAL", "Salud Total"),
                ],
                max_length=20,
                null=True,
                verbose_name="EPS",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Visible uniquement pour les managers",
                max_length=255,
                null=True,
                verbose_name="Contraseña",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="platform",
            field=models.CharField(
                choices=[("FLIRTIFY", "Flirtify")],
                default="FLIRTIFY",
                max_length=20,
                verbose_name="Plataforma",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="security_contact_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Nombre del Contacto de Seguridad",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="security_contact_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Teléfono del Contacto de Seguridad",
            ),
        ),
    ]
