# Generated by Django 6.0.1 on 2026-01-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "models_app",
            "0013_model_cedula_model_edad_model_eps_model_password_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="fecha_ingreso",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que el modelo ingresó a la agencia",
                null=True,
                verbose_name="Fecha de Ingreso",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="fecha_retiro",
            field=models.DateField(
                blank=True,
                help_text="Fecha en que el modelo se retiró de la agencia",
                null=True,
                verbose_name="Fecha de Retiro",
            ),
        ),
    ]
