# Generated by Django 6.0.1 on 2026-01-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0016_make_fecha_ingreso_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksession",
            name="session_gain_amount_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Ganancia total de cette session en USD, sauvegardée au moment de la complétion",
                max_digits=12,
                null=True,
                verbose_name="Ganancia de la Sesión (USD)",
            ),
        ),
        migrations.AddField(
            model_name="worksession",
            name="trm_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Taux de change USD/COP utilisé pour la conversion au moment de la complétion",
                max_digits=10,
                null=True,
                verbose_name="Tasa de Cambio TRM",
            ),
        ),
        migrations.AlterField(
            model_name="worksession",
            name="session_gain_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ganancia total de cette session en COP (convertie depuis USD), sauvegardée au moment de la complétion",
                max_digits=12,
                verbose_name="Ganancia de la Sesión (COP)",
            ),
        ),
    ]
